name: CD

on:
  workflow_dispatch:
    inputs:
      update-tag:
        description: "input yes means bump up tag version, and no means update the tag to top"
        required: true
        default: "no"
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      # - name: Validate CD branch
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   run: |
      #     echo It's not allowed to run CD on other branch except release.
      #     exit 1
      
      - uses: actions/checkout@v2

      - name: fetch latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      
      - name: update tag
        uses: richardsimko/update-tag@v1
        if: ${{ github.event.inputs.update-tag == 'no' }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        if: ${{ github.event.inputs.update-tag != 'no' }}
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: ${{ steps.get-latest-tag.outputs.tag }}
        id: bump-version
      
      - name: generate tag list
        run: git tag | grep v > ${{ runner.temp }}/sample-tags.txt

      - name: update sample tag list release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ runner.temp }}/sample-tags.txt
          name: "Sample Tag List"
          body: "Release to maintain sample tag list."
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "sample-tag-list"
          allowUpdates: true

      - name: generate sample zip
        run: .github/scripts/sample-zip.sh ${{ runner.temp }}/teamsfx_samples

      - name: update sample release on github
        if: ${{ github.event.inputs.update-tag == 'no' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get-latest-tag.outputs.tag }}
          artifacts: ${{ runner.temp }}/teamsfx_samples
          allowUpdates: true
      
      - name: release sample new version on github
        if: ${{ github.event.inputs.update-tag != 'no' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bump-version.outputs.new_tag }}
          artifacts: ${{ runner.temp }}/teamsfx_samples
          allowUpdates: true
          
