name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(rc, stable)"
        required: true
        default: "rc"
      bump-type:
        description: "bump type"
        required: true
        default: "patch"
  schedule:
    - cron: "0 8 * * *"
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Validate alpha release
        if: ${{ github.event_name == 'schedule' && github.ref != 'refs/heads/dev' }}
        run: |
          echo It's not allowed to run schedule release except dev branch.
          exit 1
      - name: Validate rc and stable release
        if: ${{ github.event_name == 'workflow_dispatch'&& github.ref != 'refs/heads/release' }}
        run: |
          echo It's not allowed to run release rc or stable except release branch.
          exit 1
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update templates alpha tag
        if: ${{ github.event_name == 'schedule' }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: "v0.0.0-alpha"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: update template rc tag
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: "v0.0.0-rc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        if: ${{ github.event.inputs.preid == 'stable' }}
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: ${{ github.event.inputs.bump-type }}
          RELEASE_BRANCHES: release
        id: bump-version

      - name: generate sample zip
        run: .github/scripts/sample-zip.sh ${{ runner.temp }}/teamsfx_samples
      
      - name: release sample' alpha version to github
        if: ${{ github.event_name == 'schedule' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: "v0.0.0-alpha"
          artifacts: ${{ runner.temp }}/teamsfx_samples/*.zip
          allowUpdates: true
          removeArtifacts: true

      - name: release templates' RC version to github
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: "v0.0.0-rc"
          artifacts: ${{ runner.temp }}/teamsfx_samples/*.zip
          allowUpdates: true
          removeArtifacts: true
      
      - name: release sample new version on github
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bump-version.outputs.new_tag }}
          artifacts: ${{ runner.temp }}/teamsfx_samples/*.zip
      
      - name: generate tag list
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        run: git tag | grep v > ${{ runner.temp }}/sample-tags.txt

      - name: update sample tag list release
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'stable' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ runner.temp }}/sample-tags.txt
          name: "Sample Tag List"
          body: "Release to maintain sample tag list."
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "sample-tag-list"
          allowUpdates: true
          
